# [side_effects_advanced.test.mjs](../side_effects_advanced.test.mjs)

```js
console.log("start");
await new Promise((resolve) => {
  setTimeout(resolve, 50);
});
console.info("timeout done");
await new Promise((resolve) => {
  setTimeout(resolve, 50);
});
console.warn("a warning after 2nd timeout");
console.warn("and an other warning");
writeFileSync(new URL("./toto.txt", import.meta.url), "toto");
throw new Error("in the end we throw");
```

# 1/3 logs

```console
start
timeout done
a warning after 2nd timeout
and an other warning
```

# 2/3 write file "./toto.txt"

```txt
toto
```

# 3/3 reject

```console
Error: in the end we throw
  at snapshotSideEffects.executionEffects.catch (base/side_effects_advanced.test.mjs:138:13)
  at async base/side_effects_advanced.test.mjs:124:3
```

---

<sub>
  Generated by <a href="https://github.com/jsenv/core/tree/main/packages/independent/snapshot">@jsenv/snapshot</a>
</sub>
