<!--?xml version="1.0" encoding="UTF-8"?-->
<testsuite time="[time]" timestamp="[timestamp]" tests="2" skipped="0" failures="2">
  <testcase file="error_in_test.spec.js" name="worker_thread" time="[time]" timestamp="[timestamp]" tests="1" errors="1">
    <properties>
      <property name="runtimeName" value="node_worker_thread"></property>
      <property name="runtimeVersion" value="22.11.0"></property>
    </properties>
  </testcase>
  <error type="Error">1 | throw new Error("here");
          ^
Error: here
  at base/node_client/error_in_test.spec.js:1:7</error>
  <testcase file="error_in_test.spec.js" name="child_process" time="[time]" timestamp="[timestamp]" tests="1" errors="1">
    <properties>
      <property name="runtimeName" value="node_child_process"></property>
      <property name="runtimeVersion" value="22.11.0"></property>
    </properties>
  </testcase>
  <error type="Error">1 | throw new Error("here");
          ^
Error: here
  at base/node_client/error_in_test.spec.js:1:7</error>
</testsuite>